"""Tests for agent.jira.client helpers."""

import json
from datetime import datetime, timezone
from unittest.mock import MagicMock

from agent.jira.client import (
    _extract_source_epic,
    _extract_summary_hash,
    _hash_summary,
    _normalize_summary,
    _should_set_story_points,
    build_epic_jql,
    create_obs_story,
    days_since_last_agent_comment,
    find_broad_matching_stories,
    find_or_create_obs_epic,
    format_jira_version,
    is_duplicate_story,
    needs_grooming,
)
from schemas.issue_doc import IssueDoc


class TestShouldSetStoryPoints:
    def test_none_current_allows_update(self):
        assert _should_set_story_points(None, 3) is True

    def test_zero_current_allows_update(self):
        assert _should_set_story_points(0, 5) is True

    def test_jira_default_allows_update(self):
        assert _should_set_story_points(0.42, 3) is True

    def test_existing_value_blocks_update(self):
        assert _should_set_story_points(5, 3) is False

    def test_existing_value_1_blocks_update(self):
        assert _should_set_story_points(1, 8) is False

    def test_none_new_value_blocks_update(self):
        assert _should_set_story_points(None, None) is False

    def test_existing_13_blocks_update(self):
        assert _should_set_story_points(13, 5) is False


class TestNormalizeSummary:
    def test_strips_brackets(self):
        assert _normalize_summary(
            "[Observability][metrics] Add VM metrics"
        ) == "add vm metrics"

    def test_collapses_whitespace(self):
        assert _normalize_summary("  Add   VM  metrics  ") == "add vm metrics"

    def test_lowercases(self):
        assert _normalize_summary("Add VM Metrics") == "add vm metrics"


class TestIsDuplicateStory:
    def test_duplicate_by_fingerprint(self):
        target_summary = "[Observability][metrics] Add VM metrics"
        s_hash = _hash_summary(target_summary)
        existing = [
            {
                "key": "CNV-100",
                "summary": "[Observability][metrics] Add VM metrics",
                "labels": ["cnv-observability", "epic-agent-generated"],
                "description": (
                    "some desc\n\n---\n"
                    "_auto-generated by cnv-epic-agent | "
                    f"source_epic=CNV-50 | category=metrics | "
                    f"summary_hash={s_hash}_"
                ),
            },
        ]
        assert is_duplicate_story(
            target_summary, "CNV-50", existing,
        ) is not None

    def test_different_summary_same_category_not_dup(self):
        s_hash = _hash_summary("First metrics story")
        existing = [
            {
                "key": "CNV-100",
                "summary": "First metrics story",
                "labels": ["epic-agent-generated"],
                "description": (
                    "desc\n\n---\n"
                    "_auto-generated by cnv-epic-agent | "
                    f"source_epic=CNV-50 | category=metrics | "
                    f"summary_hash={s_hash}_"
                ),
            },
        ]
        assert is_duplicate_story(
            "Second metrics story", "CNV-50", existing,
        ) is None

    def test_duplicate_by_summary(self):
        existing = [
            {
                "key": "CNV-100",
                "summary": "[Observability][metrics] Add VM metrics",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add VM metrics",
            "CNV-50", existing,
        ) is not None

    def test_not_duplicate(self):
        existing = [
            {
                "key": "CNV-100",
                "summary": "[Observability][alerts] Add alert",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add VM metrics",
            "CNV-50", existing,
        ) is None

    def test_empty_existing(self):
        assert is_duplicate_story("Any summary", "CNV-1", []) is None

    def test_duplicate_by_embedded_key(self):
        existing = [
            {
                "key": "CNV-51517",
                "summary": "Add allocated GPU metric for each VM",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add Prometheus metric "
            "for allocated GPU per VM (CNV-51517)",
            "CNV-51516", existing,
        ) is not None

    def test_duplicate_by_containment(self):
        existing = [
            {
                "key": "CNV-84407",
                "summary": "virt-launcher GPU metrics scraping "
                           "and Prometheus collector",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Implement virt-launcher "
            "GPU metrics scraping and Prometheus collector "
            "(CNV-84407)",
            "CNV-51516", existing,
        ) is not None

    def test_no_containment_for_short_summaries(self):
        existing = [
            {
                "key": "CNV-100",
                "summary": "Fix bug",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "Fix bug in GPU metrics controller",
            "CNV-50", existing,
        ) is None

    def test_equal_length_different_summaries_not_dup(self):
        existing = [
            {
                "key": "CNV-84407",
                "summary": "virt-launcher GPU metrics scraping "
                           "and Prometheus collector",
                "labels": [],
                "description": "",
            },
        ]
        assert is_duplicate_story(
            "Integrate GPU metrics into existing "
            "KubeVirt/CNV dashboards",
            "CNV-51516", existing,
        ) is None

    def test_child_key_reference_is_dup(self):
        existing = [
            {
                "key": "CNV-84168",
                "summary": "Modify LowVirtCount alerts",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][alerts] Modify LowVirtCount "
            "alerts to use 'running' status for CNV-84168",
            "CNV-81938", existing,
        ) is not None

    def test_child_containment_not_dup(self):
        existing = [
            {
                "key": "CNV-80580",
                "summary": "Add metric for VMI controller sync count",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Implement Prometheus "
            "metric for VMI controller sync count with labels",
            "CNV-81938", existing,
        ) is None

    def test_child_key_ref_plus_containment_is_dup(self):
        existing = [
            {
                "key": "CNV-80580",
                "summary": "Add metric for VMI controller sync count",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add metric for VMI "
            "controller sync count for CNV-80580",
            "CNV-81938", existing,
        ) is not None

    def test_child_qe_story_referencing_key_not_dup(self):
        existing = [
            {
                "key": "CNV-80580",
                "summary": "Add metric for VMI controller sync count",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[QE] Verify VMI controller sync count metric "
            "(CNV-80580)",
            "CNV-81938", existing,
        ) is None

    def test_child_docs_story_referencing_key_not_dup(self):
        existing = [
            {
                "key": "CNV-84168",
                "summary": "Modify LowVirtCount alerts",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Docs] Update runbook for modified LowVirtCount "
            "alerts (CNV-84168)",
            "CNV-81938", existing,
        ) is None

    def test_child_tech_token_overlap_is_dup(self):
        """Strategy 5: child description mentions same metrics/alerts."""
        existing = [
            {
                "key": "CNV-66837",
                "summary": (
                    "Add csi-volume-device-exporter DaemonSet for "
                    "storage path alerting (Storage QE help needed)"
                ),
                "labels": [],
                "description": (
                    "node_exporter exposes multipath path health but "
                    "cannot link a degraded path to the PV or VM. "
                    "csi-volume-device-exporter fills this gap by "
                    "emitting a metric that maps each CSI volume to "
                    "its underlying block device, enabling the "
                    "CSIVolumeMultipathDegraded alert. It also adds a "
                    "CSIVolumeDeviceExporterDown alert."
                ),
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][alerts] Add CSIVolumeMultipathDegraded "
            "alert for degraded multipath paths",
            "CNV-66667",
            existing,
            story_description=(
                "Emit CSIVolumeMultipathDegraded when a CSI volume "
                "has a degraded multipath path. Uses the "
                "csi-volume-device-exporter metric."
            ),
        ) is not None

    def test_child_tech_token_overlap_qe_not_dup(self):
        """Strategy 5 does NOT fire for QE/docs proposals."""
        existing = [
            {
                "key": "CNV-66837",
                "summary": (
                    "Add csi-volume-device-exporter DaemonSet"
                ),
                "labels": [],
                "description": (
                    "Adds CSIVolumeMultipathDegraded alert and "
                    "CSIVolumeDeviceExporterDown alert via "
                    "csi-volume-device-exporter."
                ),
                "_from_children": True,
            },
        ]
        # QE proposals intentionally reference the same tokens
        assert is_duplicate_story(
            "[QE] Verify CSIVolumeMultipathDegraded alert fires "
            "correctly for csi-volume-device-exporter",
            "CNV-66667",
            existing,
            story_description="",
        ) is None

    def test_child_tech_token_overlap_single_token_not_dup(self):
        """Strategy 5 requires ≥2 overlapping tokens."""
        existing = [
            {
                "key": "CNV-66837",
                "summary": "Add csi-volume-device-exporter DaemonSet",
                "labels": [],
                "description": "Adds CSIVolumeMultipathDegraded alert.",
                "_from_children": True,
            },
        ]
        # Proposed story only shares one token ("CSIVolumeMultipathDegraded")
        assert is_duplicate_story(
            "[Observability][metrics] Track VMI memory balloon "
            "stats with CSIVolumeMultipathDegraded label",
            "CNV-66667",
            existing,
            story_description="Add kubevirt_vmi_memory_balloon_bytes.",
        ) is None

    def test_child_exact_match_still_dup(self):
        existing = [
            {
                "key": "CNV-80580",
                "summary": "[Observability][metrics] Add metric "
                           "for VMI controller sync count",
                "labels": [],
                "description": "",
                "_from_children": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add metric for VMI "
            "controller sync count",
            "CNV-81938", existing,
        ) is not None


class TestBroadSearchDedup:
    """Verify _from_broad_search entries use only strategies 2+4."""

    def test_broad_exact_summary_match_is_dup(self):
        existing = [
            {
                "key": "CNV-999",
                "summary": "[Observability][metrics] Add GPU metric",
                "_from_broad_search": True,
            },
        ]
        result = is_duplicate_story(
            "[Observability][metrics] Add GPU metric",
            "CNV-50", existing,
        )
        assert result == "CNV-999"

    def test_broad_containment_match_is_dup(self):
        existing = [
            {
                "key": "CNV-888",
                "summary": "Add GPU passthrough metric",
                "_from_broad_search": True,
            },
        ]
        result = is_duplicate_story(
            "[Observability][metrics] Add GPU passthrough "
            "metric for VM allocation",
            "CNV-50", existing,
        )
        assert result == "CNV-888"

    def test_broad_fingerprint_ignored(self):
        target = "[Observability][metrics] Add GPU metric"
        s_hash = _hash_summary(target)
        existing = [
            {
                "key": "CNV-777",
                "summary": "Unrelated summary",
                "description": (
                    f"source_epic=CNV-50 summary_hash={s_hash}"
                ),
                "_from_broad_search": True,
            },
        ]
        assert is_duplicate_story(
            target, "CNV-50", existing,
        ) is None

    def test_broad_key_reference_ignored(self):
        existing = [
            {
                "key": "CNV-666",
                "summary": "Some unrelated feature",
                "_from_broad_search": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability] Add metric (CNV-666)",
            "CNV-50", existing,
        ) is None

    def test_broad_no_match_returns_none(self):
        existing = [
            {
                "key": "CNV-555",
                "summary": "Completely different topic",
                "_from_broad_search": True,
            },
        ]
        assert is_duplicate_story(
            "[Observability][metrics] Add GPU metric",
            "CNV-50", existing,
        ) is None


class TestFindBroadMatchingStories:
    """Unit tests for find_broad_matching_stories."""

    def test_builds_jql_and_returns_tagged_entries(self):
        mock_client = MagicMock()
        mock_issue = MagicMock()
        mock_issue.key = "CNV-123"
        mock_issue.fields.summary = "Add migration metric"
        mock_client.search_issues.return_value = [mock_issue]

        cfg = {"jira": {"default_project": "CNV"}}
        results = find_broad_matching_stories(
            mock_client, cfg, "CNV-50",
            ["migration", "multicast"],
        )

        assert len(results) == 1
        assert results[0]["key"] == "CNV-123"
        assert results[0]["_from_broad_search"] is True

        jql_arg = mock_client.search_issues.call_args[0][0]
        assert "migration" in jql_arg
        assert "multicast" in jql_arg

    def test_filters_short_keywords(self):
        mock_client = MagicMock()
        mock_client.search_issues.return_value = []

        cfg = {"jira": {"default_project": "CNV"}}
        results = find_broad_matching_stories(
            mock_client, cfg, "CNV-50",
            ["vm", "cpu", "gpu"],
        )
        assert results == []
        mock_client.search_issues.assert_not_called()

    def test_skips_source_epic_key(self):
        mock_client = MagicMock()
        mock_issue_self = MagicMock()
        mock_issue_self.key = "CNV-50"
        mock_issue_self.fields.summary = "Source epic"
        mock_issue_other = MagicMock()
        mock_issue_other.key = "CNV-100"
        mock_issue_other.fields.summary = "Other story"
        mock_client.search_issues.return_value = [
            mock_issue_self, mock_issue_other,
        ]

        cfg = {"jira": {"default_project": "CNV"}}
        results = find_broad_matching_stories(
            mock_client, cfg, "CNV-50", ["migration"],
        )
        assert len(results) == 1
        assert results[0]["key"] == "CNV-100"

    def test_caps_keywords_at_five(self):
        mock_client = MagicMock()
        mock_client.search_issues.return_value = []

        cfg = {"jira": {"default_project": "CNV"}}
        keywords = [
            "migration", "multicast", "infiniband",
            "hotplug", "network", "storage", "backup",
        ]
        find_broad_matching_stories(
            mock_client, cfg, "CNV-50", keywords,
        )

        jql_arg = mock_client.search_issues.call_args[0][0]
        assert jql_arg.count('summary ~') == 5

    def test_handles_jira_error_gracefully(self):
        mock_client = MagicMock()
        mock_client.search_issues.side_effect = Exception(
            "Jira unavailable"
        )

        cfg = {"jira": {"default_project": "CNV"}}
        results = find_broad_matching_stories(
            mock_client, cfg, "CNV-50", ["migration"],
        )
        assert results == []


class TestFindOrCreateObsEpic:
    """Verify obs epic search uses label + version, not summary."""

    _CFG = {
        "jira": {"version_format": "CNV v{version}"},
        "creation": {
            "project": "CNV",
            "epic_label": "cnv-observability",
            "obs_epic_label": "cnv-grooming-agent",
            "component": "CNV Install, Upgrade and Operators",
            "epic_summary_format": (
                "[Observability] CNV {version} — stories"
            ),
        },
    }

    def test_search_uses_label_and_version(self):
        mock_client = MagicMock()
        mock_issue = MagicMock()
        mock_issue.key = "CNV-999"
        mock_issue.fields.summary = "Existing obs epic"
        mock_client.search_issues.return_value = [mock_issue]

        result = find_or_create_obs_epic(
            mock_client, self._CFG, "5.0.0", dry_run=True,
        )

        jql = mock_client.search_issues.call_args[0][0]
        assert 'cnv-grooming-agent' in jql
        assert 'fixVersion = "CNV v5.0.0"' in jql
        assert '"Target Version" = "CNV v5.0.0"' in jql
        assert 'summary ~' not in jql
        assert result["key"] == "CNV-999"
        assert result["created"] is False

    def test_dry_run_returns_placeholder(self):
        mock_client = MagicMock()
        mock_client.search_issues.return_value = []

        result = find_or_create_obs_epic(
            mock_client, self._CFG, "5.0.0", dry_run=True,
        )

        assert result["key"] == "(DRY-RUN)"
        assert "5.0.0" in result["summary"]

    def test_create_sets_labels_and_version(self):
        mock_client = MagicMock()
        mock_client.search_issues.return_value = []
        mock_issue = MagicMock()
        mock_issue.key = "CNV-1000"
        mock_client.create_issue.return_value = mock_issue

        result = find_or_create_obs_epic(
            mock_client, self._CFG, "5.0.0", dry_run=False,
        )

        assert result["key"] == "CNV-1000"
        assert result["created"] is True

        fields = mock_client.create_issue.call_args[1]["fields"]
        assert "cnv-observability" in fields["labels"]
        assert "cnv-grooming-agent" in fields["labels"]
        assert fields["fixVersions"] == [
            {"name": "CNV v5.0.0"},
        ]


class TestDaysSinceLastAgentComment:
    """Verify agent comment age detection."""

    def test_no_comments_returns_none(self):
        mock_client = MagicMock()
        mock_issue = MagicMock()
        mock_issue.fields.comment.comments = []
        mock_client.issue.return_value = mock_issue

        assert days_since_last_agent_comment(
            mock_client, "CNV-100",
        ) is None

    def test_no_agent_comment_returns_none(self):
        mock_client = MagicMock()
        comment = MagicMock()
        comment.body = "Regular human comment"
        comment.created = "2026-01-01T00:00:00.000+0000"
        mock_issue = MagicMock()
        mock_issue.fields.comment.comments = [comment]
        mock_client.issue.return_value = mock_issue

        assert days_since_last_agent_comment(
            mock_client, "CNV-100",
        ) is None

    def test_agent_comment_returns_days(self):
        mock_client = MagicMock()
        now = datetime.now(timezone.utc)
        comment = MagicMock()
        comment.body = "[Epic Agent] Please add more detail."
        comment.created = now.isoformat()
        mock_issue = MagicMock()
        mock_issue.fields.comment.comments = [comment]
        mock_client.issue.return_value = mock_issue

        result = days_since_last_agent_comment(
            mock_client, "CNV-100",
        )
        assert result is not None
        assert result < 1.0

    def test_picks_most_recent_agent_comment(self):
        mock_client = MagicMock()
        old_comment = MagicMock()
        old_comment.body = "[Epic Agent] Old reminder."
        old_comment.created = "2025-01-01T00:00:00.000+0000"
        new_comment = MagicMock()
        new_comment.body = "[Epic Agent] Recent reminder."
        new_comment.created = "2026-05-04T00:00:00.000+0000"
        mock_issue = MagicMock()
        mock_issue.fields.comment.comments = [
            old_comment, new_comment,
        ]
        mock_client.issue.return_value = mock_issue

        result = days_since_last_agent_comment(
            mock_client, "CNV-100",
        )
        assert result is not None
        assert result < 400


class TestFingerprintFormat:
    def test_create_obs_story_embeds_fingerprint(self):
        mock_client = MagicMock()
        mock_issue = MagicMock()
        mock_issue.key = "CNV-999"
        mock_client.create_issue.return_value = mock_issue

        cfg = {
            "creation": {
                "project": "CNV",
                "component": "Test",
                "story_label": "epic-agent-generated",
                "epic_label": "cnv-observability",
            },
        }
        summary = "[Observability][metrics] Add VM metrics"
        issue, warnings = create_obs_story(
            mock_client, cfg, "CNV-OBS-1", "CNV-50",
            summary, "Body text",
            category="metrics",
        )
        created_fields = mock_client.create_issue.call_args[1]["fields"]
        desc = created_fields["description"]

        fake_story = {"description": desc}
        assert _extract_source_epic(fake_story) == "CNV-50"
        extracted_hash = _extract_summary_hash(fake_story)
        assert extracted_hash == _hash_summary(summary)
        assert "category=metrics" in desc

    def test_hash_summary_deterministic(self):
        h1 = _hash_summary("Same summary text")
        h2 = _hash_summary("Same summary text")
        assert h1 == h2

    def test_hash_summary_differs(self):
        h1 = _hash_summary("First summary")
        h2 = _hash_summary("Second summary")
        assert h1 != h2


class TestFormatJiraVersion:
    def test_default_format(self):
        cfg = {"jira": {"version_format": "CNV v{version}"}}
        assert format_jira_version(cfg, "4.22") == "CNV v4.22"

    def test_custom_format(self):
        cfg = {"jira": {"version_format": "OCP-{version}"}}
        assert format_jira_version(cfg, "4.23.0") == "OCP-4.23.0"

    def test_fallback_when_no_config(self):
        assert format_jira_version({}, "4.22") == "CNV v4.22"


class TestBuildEpicJql:
    """Verify JQL filter building for epic scans."""

    _CFG = {
        "jira": {
            "default_project": "CNV",
            "default_since_days": 30,
            "jql_template": (
                "project = {project} AND type = Epic"
                " AND created >= -{since_days}d"
            ),
        },
    }

    def test_default_jql(self):
        jql = build_epic_jql(self._CFG)
        assert "project = CNV" in jql
        assert "type = Epic" in jql
        assert "created >= -30d" in jql

    def test_custom_project_and_days(self):
        jql = build_epic_jql(
            self._CFG, project="OCPBUGS", since_days=7,
        )
        assert "project = OCPBUGS" in jql
        assert "-7d" in jql

    def test_component_filter(self):
        jql = build_epic_jql(self._CFG, component="Virtualization")
        assert 'component = "Virtualization"' in jql

    def test_fix_version_filter(self):
        jql = build_epic_jql(self._CFG, fix_version="4.22")
        assert 'fixVersion = "4.22"' in jql

    def test_target_version_filter(self):
        jql = build_epic_jql(
            self._CFG, target_version="4.22.0",
        )
        assert '"Target Version" = "4.22.0"' in jql

    def test_single_label_filter(self):
        jql = build_epic_jql(self._CFG, labels=["gpu"])
        assert 'labels = "gpu"' in jql

    def test_multiple_labels_filter(self):
        jql = build_epic_jql(
            self._CFG, labels=["gpu", "cnv-4.22"],
        )
        assert 'labels = "gpu"' in jql
        assert 'labels = "cnv-4.22"' in jql

    def test_both_versions_combined_with_or(self):
        jql = build_epic_jql(
            self._CFG,
            fix_version="CNV v4.22",
            target_version="CNV v4.22",
        )
        assert 'fixVersion = "CNV v4.22"' in jql
        assert '"Target Version" = "CNV v4.22"' in jql
        assert " OR " in jql

    def test_all_filters_combined(self):
        jql = build_epic_jql(
            self._CFG,
            project="CNV",
            since_days=14,
            component="Virtualization",
            fix_version="4.22",
            target_version="4.22.0",
            labels=["gpu"],
        )
        assert "project = CNV" in jql
        assert "-14d" in jql
        assert 'component = "Virtualization"' in jql
        assert 'fixVersion = "4.22"' in jql
        assert '"Target Version" = "4.22.0"' in jql
        assert 'labels = "gpu"' in jql

    def test_skip_label_excluded_by_default(self):
        jql = build_epic_jql(self._CFG)
        assert 'labels != "cnv-grooming-agent-skip"' in jql

    def test_skip_label_from_config(self):
        cfg = {**self._CFG, "grooming": {"skip_label": "my-skip"}}
        jql = build_epic_jql(cfg)
        assert 'labels != "my-skip"' in jql

    def test_no_filters_no_extra_clauses(self):
        jql = build_epic_jql(self._CFG)
        assert "component" not in jql
        assert "fixVersion" not in jql
        assert "Target Version" not in jql


class TestNeedsGrooming:
    """Verify that needs_grooming flags epics with insufficient detail."""

    _CFG = {
        "grooming": {
            "label": "grooming",
            "min_description_length": 50,
            "min_children": 1,
        },
    }

    def test_short_desc_no_children_needs_grooming(self):
        epic = IssueDoc(key="CNV-1", summary="Test", description="Short")
        assert needs_grooming(epic, [], self._CFG) is True

    def test_long_desc_no_children_ok(self):
        epic = IssueDoc(
            key="CNV-2", summary="Test", description="A" * 60,
        )
        assert needs_grooming(epic, [], self._CFG) is False

    def test_short_desc_with_children_ok(self):
        epic = IssueDoc(key="CNV-3", summary="Test", description="Short")
        child = IssueDoc(
            key="CNV-4", summary="Child", description="child desc",
        )
        assert needs_grooming(epic, [child], self._CFG) is False

    def test_empty_desc_no_children_needs_grooming(self):
        epic = IssueDoc(key="CNV-5", summary="Test", description="")
        assert needs_grooming(epic, [], self._CFG) is True

    def test_none_desc_no_children_needs_grooming(self):
        epic = IssueDoc(key="CNV-6", summary="Test", description="")
        assert needs_grooming(epic, [], self._CFG) is True

    def test_defaults_when_no_grooming_config(self):
        epic = IssueDoc(key="CNV-7", summary="Test", description="Short")
        assert needs_grooming(epic, [], {}) is True
